// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Projeto - docker",
            "email": "projeto@email.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/todo": {
            "get": {
                "description": "Esta rota retorna todas os ToDos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Lista todos os ToDos ativos.",
                "operationId": "Todo.List",
                "responses": {
                    "200": {
                        "description": "Requisição realizada com sucesso.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Todo"
                            }
                        }
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "Esta rota Cria um ToDo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Cria um ToDo.",
                "operationId": "Todo.Create",
                "parameters": [
                    {
                        "description": "Parametros necessários para inserir um ToDo.",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Todo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requisição realizada com sucesso.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Todo"
                            }
                        }
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/todo/restore/{id}": {
            "put": {
                "description": "Esta rota Restora um ToDo deletado.",
                "tags": [
                    "Todo"
                ],
                "summary": "Restora um ToDo.",
                "operationId": "Todo.RestoreToDo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de um ToDo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Requisição realizada com sucesso"
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/todo/{id}": {
            "get": {
                "description": "Esta rota retorna todas os ToDos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Retorna os detalhes de um ToDo",
                "operationId": "Todo.GetByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de um ToDo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requisição realizada com sucesso.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Todo"
                            }
                        }
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            },
            "put": {
                "description": "Esta rota Atualiza a descrição de um ToDo.",
                "tags": [
                    "Todo"
                ],
                "summary": "Atualização do ToDo.",
                "operationId": "Todo.Create",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de um ToDo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parametros necessários para inserir um ToDo.",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Todo"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Requisição realizada com sucesso"
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "Esta rota Deleta um ToDo.",
                "tags": [
                    "Todo"
                ],
                "summary": "Deleta um ToDo.",
                "operationId": "Todo.DeleteToDo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de um ToDo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Requisição realizada com sucesso"
                    },
                    "422": {
                        "description": "Algum dos dados informados não pôde ser processado. Verifique os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Ocorreu um erro inesperado. Por favor, contate o suporte.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    },
                    "503": {
                        "description": "A base de dados está temporariamente indisponível.",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.Todo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "response.ErrorMessage": {
            "type": "object",
            "properties": {
                "error": {},
                "invalid_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.InvalidField"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "response.InvalidField": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "field_name": {
                    "type": "string"
                }
            }
        },
        "response.Todo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "bearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Todo API",
	Description:      "Todo API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
