basePath: /api
definitions:
  request.Todo:
    properties:
      description:
        type: string
      is_active:
        type: boolean
    type: object
  request.UpdateTodo:
    properties:
      description:
        type: string
    type: object
  response.ErrorMessage:
    properties:
      error: {}
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  response.InvalidField:
    properties:
      description:
        type: string
      field_name:
        type: string
    type: object
  response.Todo:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      updated_at:
        type: string
    type: object
info:
  contact:
    email: projeto@email.com
    name: Projeto - docker
  description: Todo API
  title: Todo API
  version: "1.0"
paths:
  /todo:
    get:
      description: Esta rota retorna todas os ToDos.
      operationId: Todo.List
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Todo'
            type: array
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Lista todos os ToDos ativos.
      tags:
      - Todo
    post:
      description: Esta rota Cria um ToDo.
      operationId: Todo.Create
      parameters:
      - description: Parametros necessários para inserir um ToDo.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Todo'
            type: array
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Cria um ToDo.
      tags:
      - Todo
  /todo/{id}:
    delete:
      description: Esta rota Deleta um ToDo.
      operationId: Todo.DeleteToDo
      parameters:
      - description: UUID de um ToDo
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Requisição realizada com sucesso
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Deleta um ToDo.
      tags:
      - Todo
    get:
      description: Esta rota retorna todas os ToDos.
      operationId: Todo.GetByID
      parameters:
      - description: UUID de um ToDo
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Todo'
            type: array
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Retorna os detalhes de um ToDo
      tags:
      - Todo
    put:
      description: Esta rota Atualiza a descrição de um ToDo.
      operationId: Todo.Update
      parameters:
      - description: UUID de um ToDo
        in: path
        name: id
        required: true
        type: string
      - description: Parametros necessários para inserir um ToDo.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTodo'
      responses:
        "204":
          description: Requisição realizada com sucesso
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Atualização do ToDo.
      tags:
      - Todo
  /todo/restore/{id}:
    put:
      description: Esta rota Restora um ToDo deletado.
      operationId: Todo.RestoreToDo
      parameters:
      - description: UUID de um ToDo
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Requisição realizada com sucesso
        "422":
          description: Algum dos dados informados não pôde ser processado. Verifique
            os dados fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Restora um ToDo.
      tags:
      - Todo
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
